### PR TITLE
Replace querystring with URLSearchParams

### LINKED ISSUE #13: TypeError: querystring_1.default.encode is not a function when searching for movie
**Describe the bug**
When I call the following function

`const movies = await tmdb.search.movies({ query: 'Babylon' });`

I get this error
`TypeError: querystring_1.default.encode is not a function` in `search.ts:49`

However, it seems the code is working in my console as I can log stuff related to the search results. See Additional information why that might be the case

**To Reproduce**
1. Call `tmdb.search.movies` with some `query` parameter

**Expected behavior**
A search result should be returned

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [firefox]
 - Version [110]
 
 **Additional information**
I also get the following warning
```
Module "querystring" has been externalized for browser compatibility. Cannot access "querystring.encode" in client code. See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

### PR DESCRIPTION
**Pull request by Hoidi**
Resolves #13 

Some things I would appreciate feedback on. Other feedback is ofcourse welcome
- Naming for the new interfaces `PageOptions` and `LocaleOptions`. Not the greatest names but they made it easier to work with `URLSearchParams`
- Lots of code checking if the `options` is `undefined`. Should I create a new utils function for this logic?
- Should I bump the version to `0.1.5`?

### CODE REVIEW

File: src/types/page.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+export interface PageOptions {
+    page?: number;
+}
+  
+export interface LocaleOptions extends PageOptions {
+    region?: string;
+    language?: string;
+}
```
Comment (Der-Penz) [inline src/types/page.ts:8]: Using this would interfere with my newly created way to handle options by using union types on different base options interfaces to create the needed option parameters in my PR #12. I think we should decide on one way to handle Option parameters and maybe add one utility Class/Function which would handle everything like checking for undefined options.

**Comment by blakejoy** [comment]
I'm down for making this change since it seems like the use case extends further than just server side utilizing this lib

File: src/types/page.ts (hunk 1 above)
Comment (Hoidi) [reply src/types/page.ts:8]: I'm kinda new to the whole web development world so forgive my lack of knowledge, but how does this interfere with your changes more than the naming on things? I can't find where you're using union types in your PR 🤔 

Anyway, I don't have any stong opinions regarding this. You (or maybe @blakejoy) can decide and I'll adapt

Comment (Hoidi) [reply src/types/page.ts:8]: @Der-Penz Have you given it any tought?

Comment (Der-Penz) [reply src/types/page.ts:8]: Sorry for the delayed answer, I overlooked your comment. "Interfer" might be the wrong word. I just mean it would be a different way on how to at those options. I proposed to make an interface for each option and in the endpoint you could just add all of the options by using union types. you extended the PageOption interface, while I proposed to make all different interfaces and later add them with union types.
But as you already said @blakejoy should decide.

Comment (blakejoy) [reply src/types/page.ts:8]: You've been more intertwined with this as of lately so however you think will implement the necessary changes and not break anything. I'm for @Der-Penz @Hoidi

Comment (Der-Penz) [reply src/types/page.ts:8]: Maybe you could merge my pull request #12  if everything is fine with it and after it, Hoidi can remove its PageOptions and Localoptions and update the type/options.ts to include a Localoptions interface which he can use then.

Comment (blakejoy) [reply src/types/page.ts:8]: Merged

**Review by Der-Penz — CHANGES_REQUESTED** [review]
Looks fine to me. But maybe adding a method for parsing the options would be helpful, so we don't need to always check for undefined options. It would be cleaner in my opinion because it is kinda repetitive to check it all the time.

E.g:
```javascript
function parseOptions(options){
  return options 
      ? new URLSearchParams(Object.entries(options)).toString() 
      :  '';
}
```

**Comment by Der-Penz** [comment]
I think this can be merged now.

**Comment by blakejoy** [comment]
bump the version and we can get this merged @Hoidi
