### PR TITLE
[i18n]Fixed all implemented methods that should allow LanguageOptions to be passed

### LINKED ISSUE #39: Is passing language query param possible?
Hi. Thanks for writing this useful tool.

My question is the following:
I would like to query the [movie details](https://developer.themoviedb.org/reference/movie-details), using a language that is not English.

Is this possible?

Thanks in advance.

### PR DESCRIPTION
**Pull request by jeremyVignelles**
Everywhere the API expects a language option, I updated the parameters so that they match the expected API options.

Fixes #39

NOTE: I tried to make no breaking changes, but there was a bad options typing in methods TvShowEndpoint/{airingToday,popular,topRated} : The `RegionOption` was included here by mistake.

This is technically a breaking change for codes that incorrecly use the API

### CODE REVIEW

**Comment by reaver585** [comment]
@blakejoy any chance this PR could be merged some time soon?

**Comment by blakejoy** [comment]
I can take a look today/tomorrow

**Comment by reaver585** [comment]
Thanks a ton.

File: src/endpoints/movies.ts [hunk 1]
```diff
@@ -31,19 +31,28 @@ import {
...
 export class MoviesEndpoint extends BaseEndpoint {
   constructor(protected readonly accessToken: string) {
     super(accessToken);
   }
 
   async details<T extends AppendToResponseMovieKey[] | undefined>(
     id: number,
-    appendToResponse?: T
+    appendToResponse?: T,
+    language?: string
```
Comment (blakejoy) [inline src/endpoints/movies.ts:49]: Should this be updated to be an options param passed here ?

File: src/endpoints/tv-shows.ts [hunk 2]
```diff
@@ -115,7 +136,7 @@ export class TvShowsEndpoint extends BaseEndpoint {
     );
   }
 
-  async similar(id: number, options?: PageOption): Promise<SimilarTvShows> {
+  async similar(id: number, options?: LanguageOption & PageOption): Promise<SimilarTvShows> {
```
Comment (blakejoy) [inline src/endpoints/tv-shows.ts:139]: Should this be combined into it's own options type instead of using an intersection (applies to all cases)?

File: src/endpoints/tv-shows.ts [hunk 3]
```diff
@@ -33,19 +34,35 @@ import {
 
 const BASE_TV = '/tv';
 
+export interface TvImageSearchOptions extends LanguageOption {
```
Comment (blakejoy) [inline src/endpoints/tv-shows.ts:37]: Can we move this to the appropriate types file?

**Comment by blakejoy** [comment]
Few comments @jeremyVignelles

File: src/endpoints/tv-shows.ts (hunk 2 above)
Comment (jeremyVignelles) [reply src/endpoints/tv-shows.ts:140]: There were several places where this was done. I'd argue that, as  long as it stays short, it's easier to update options by composing them rather than having a type or an interfaced declare in another file.

File: src/endpoints/tv-shows.ts (hunk 3 above)
Comment (jeremyVignelles) [reply src/endpoints/tv-shows.ts]: OK, moved :)

**Comment by jeremyVignelles** [comment]
@blakejoy : up 🙂

**Comment by blakejoy** [comment]
I’ll take a look at this today 😎

**Comment by jeremyVignelles** [comment]
Did you have time to review yet ? any comments left ?

**Review by blakejoy — APPROVED** [review]

**Comment by blakejoy** [comment]
Merged
